
baseurl = "https://boot-error.github.io" # Controls base URL
languageCode = "en-US" # Controls html lang attribute
title = "Vighnesh's Musings" # Homepage title and page title suffix
paginate = 5 # Number of posts to show before paginating

enableRobotsTXT = false # Suggested, enable robots.txt file
googleAnalytics = "UA-162174989-1" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[params]
  description = "I write stuff here" # Suggested, controls homepage description meta
  author = "Boot-Error" # Optional, controls author name display on posts
  show_menu = true # Optional, set false to disable menu entirely

[menu]
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 0
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    weight = 2
    identifier = "about"
    url = "/about/"
